## 1.1创建多维数组

In [1]:
import numpy as np

In [2]:
data1 = [5, 7, 9, 20]    #列表
arr1 = np.array(data1)
arr1

array([ 5,  7,  9, 20])

In [3]:
data2 = (5, 7, 9, 20)     #元组
arr2 = np.array(data2)
arr2

array([ 5,  7,  9, 20])

In [4]:
data3 = [[1, 2, 3, 4],[5, 6, 7, 8]]   #多维数组
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr3.shape

(2, 4)

In [6]:
arr3.dtype

dtype('int32')

In [7]:
data4 = [1.2, 2, 3.45, 5]
arr4 = np.array(data4)
arr4

array([1.2 , 2.  , 3.45, 5.  ])

In [8]:
arr4.dtype

dtype('float64')

In [9]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.empty((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr5 = np.ones_like(arr3)
arr5

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
arr5.dtype

dtype('int32')

## 1.2数组属性

In [18]:
data = [[2, 4, 5],[3,5, 7]]
arr = np.array(data)
arr

array([[2, 4, 5],
       [3, 5, 7]])

In [19]:
arr.ndim

2

In [20]:
arr.size

6

In [21]:
arr.itemsize

4

In [22]:
arr.dtype

dtype('int32')

## 1.3数组类型与变换

In [23]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [24]:
arr1.dtype

dtype('int32')

In [25]:
arr2 = np.arange(5,dtype='float64')
arr2

array([0., 1., 2., 3., 4.])

In [26]:
arr2.dtype

dtype('float64')

In [27]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [28]:
arr1.dtype

dtype('int32')

In [29]:
arr2 = arr1.astype(np.float64)
arr2

array([0., 1., 2., 3., 4., 5.])

In [30]:
arr2.dtype

dtype('float64')

In [31]:
arr3 = arr1.astype('string_')
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [32]:
arr3.dtype

dtype('S11')

In [33]:
arr = np.array([2.3, 7.5, 5.6, 9.8])
arr

array([2.3, 7.5, 5.6, 9.8])

In [34]:
arr.astype('int32')

array([2, 7, 5, 9])

In [35]:
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [36]:
arr3.astype(np.int32)

array([0, 1, 2, 3, 4, 5])

In [37]:
arr = np.array(['2', 'hello'])
arr

array(['2', 'hello'], dtype='<U5')

In [38]:
arr.astype('int32')

ValueError: invalid literal for int() with base 10: 'hello'

In [39]:
arr1 = np.arange(10)
arr1.dtype

dtype('int32')

In [40]:
arr2 = np.ones(5)
arr2.dtype

dtype('float64')

In [41]:
arr3 = arr1.astype(arr2.dtype)
arr3.dtype

dtype('float64')

In [42]:
arr = np.arange(3)
arr.dtype

dtype('int32')

In [43]:
arr.astype('float64')

array([0., 1., 2.])

In [44]:
arr

array([0, 1, 2])

# 1.3数据变换

In [45]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr = np.array([[3, 4, 5],[1, 2, 3]])
arr.reshape((3,2))

array([[3, 4],
       [5, 1],
       [2, 3]])

In [48]:
arr = np.arange(12)
arr.reshape((3,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
arr = np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [52]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
arr2 = np.arange(12,24).reshape(3,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
np.concatenate([arr1, arr2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
np.concatenate([arr1, arr2],axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [58]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [60]:
arr = np.arange(12).reshape((6,2))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [61]:
np.split(arr,[2, 4])

[array([[0, 1],
        [2, 3]]), array([[4, 5],
        [6, 7]]), array([[ 8,  9],
        [10, 11]])]

In [62]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
arr.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [64]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [65]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [66]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 1.4随机数

In [67]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[189, 100, 113, 115],
       [109, 146, 191, 130],
       [111, 102, 151, 187],
       [131, 153, 119, 104],
       [121, 142, 106, 170]])

In [68]:
arr = np.random.randn(2, 3, 5)
arr

array([[[ 1.57552831, -0.03844265, -1.57687329,  1.63434437,
          2.08640694],
        [ 1.14522244,  0.13930427,  1.18958565, -1.53746026,
          2.05324272],
        [-1.55497165, -0.66612201, -1.23153962,  1.22749603,
         -0.47564033]],

       [[-0.95279727,  0.63247826,  0.30504872,  0.66735843,
         -0.74636145],
        [-1.31301376,  0.24397392,  1.40681137,  0.08472011,
          0.75561781],
        [-1.19416579,  0.19543635, -0.50820577,  1.05192733,
          0.07255312]]])

In [69]:
arr = np.random.normal(4, 5, size=(3,5))
arr

array([[-0.15532185,  4.30119323,  3.29916695,  3.84670708,  0.50111216],
       [ 6.07242058, -0.22697321,  2.60556393,  2.14626198,  7.32173104],
       [ 3.45775388,  9.48129733,  2.47439643,  1.28317488,  6.38279118]])

In [70]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[111, 133, 182, 174],
       [167, 170, 143, 172],
       [100, 141, 192, 127],
       [135, 166, 156, 143],
       [106, 125, 154, 113]])

In [71]:
np.random.permutation(arr)

array([[100, 141, 192, 127],
       [111, 133, 182, 174],
       [167, 170, 143, 172],
       [135, 166, 156, 143],
       [106, 125, 154, 113]])

In [72]:
arr

array([[111, 133, 182, 174],
       [167, 170, 143, 172],
       [100, 141, 192, 127],
       [135, 166, 156, 143],
       [106, 125, 154, 113]])

In [73]:
arr = np.random.randint(100, 200, size=(5, 4))
arr

array([[198, 127, 176, 177],
       [163, 181, 134, 130],
       [129, 183, 127, 166],
       [194, 173, 119, 197],
       [119, 199, 196, 192]])

In [74]:
np.random.shuffle(arr)

In [75]:
arr

array([[163, 181, 134, 130],
       [129, 183, 127, 166],
       [194, 173, 119, 197],
       [198, 127, 176, 177],
       [119, 199, 196, 192]])

## 2 索引和切片

In [76]:
import numpy as np

In [77]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr[3]

3

In [79]:
arr[-1]

9

In [80]:
arr[2] = 123
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [81]:
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [82]:
arr[3] = 88
arr

array([  0,   1, 123,  88,   4,   5,   6,   7,   8,   9])

In [83]:
arr1 = arr[-3:-1]
arr1

array([7, 8])

In [84]:
arr1[:] = 77
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [85]:
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [86]:
arr1 = arr[1].copy()
arr1 = 34
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [87]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [88]:
arr[0]

array([0, 1, 2, 3, 4])

In [89]:
arr[2]

array([10, 11, 12, 13, 14])

In [90]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
arr[0][3]

3

In [92]:
arr[2,3]  #两种方法等价

13

In [93]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [94]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
old = arr[0].copy()
arr[0] = 12
arr

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [96]:
arr[0] = old
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [97]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [98]:
arr[1, 1]

array([ 9, 10, 11])

In [99]:
arr[0, 1, 2]

5

In [100]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [101]:
arr[2:5]

array([2, 3, 4])

In [102]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
arr[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [104]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [105]:
arr[:, 1]

array([ 1,  4,  7, 10])

In [106]:
arr[:, 1:2]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [107]:
arr[2:, 1:]

array([[ 7,  8],
       [10, 11]])

In [108]:
fruits = np.array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'])
datas = np.random.randint(-1, 1, size=(7,5))

In [109]:
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [110]:
datas

array([[-1, -1, -1, -1, -1],
       [-1, -1,  0, -1,  0],
       [ 0, -1,  0, -1, -1],
       [-1, -1, -1,  0,  0],
       [-1,  0, -1,  0, -1],
       [-1,  0, -1,  0,  0],
       [-1,  0, -1,  0, -1]])

In [111]:
fruits == 'pear'

array([False, False,  True, False,  True, False,  True])

In [112]:
datas[fruits == 'pear']

array([[ 0, -1,  0, -1, -1],
       [-1,  0, -1,  0, -1],
       [-1,  0, -1,  0, -1]])

In [113]:
datas[fruits != 'pear']

array([[-1, -1, -1, -1, -1],
       [-1, -1,  0, -1,  0],
       [-1, -1, -1,  0,  0],
       [-1,  0, -1,  0,  0]])

In [114]:
datas[(fruits == 'apple') | (fruits == 'banana')]

array([[-1, -1, -1, -1, -1],
       [-1, -1,  0, -1,  0],
       [-1, -1, -1,  0,  0],
       [-1,  0, -1,  0,  0]])

In [115]:
datas[fruits == 'pear',2:]

array([[ 0, -1, -1],
       [-1,  0, -1],
       [-1,  0, -1]])

In [116]:
datas[fruits == 'pear',2]

array([ 0, -1, -1])

In [117]:
datas[datas == 0] = 1
datas

array([[-1, -1, -1, -1, -1],
       [-1, -1,  1, -1,  1],
       [ 1, -1,  1, -1, -1],
       [-1, -1, -1,  1,  1],
       [-1,  1, -1,  1, -1],
       [-1,  1, -1,  1,  1],
       [-1,  1, -1,  1, -1]])

In [118]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [119]:
arr[[1, 3, 2]]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8]])

In [120]:
arr[[3, 2]][:, [2, 1]]

array([[11, 10],
       [ 8,  7]])

In [121]:
arr[np.ix_([3,2],[2, 1])]

array([[11, 10],
       [ 8,  7]])

## 3数组计算

In [122]:
a = [1, 2, 3]
b = []
for i in a:
    b.append(i * 10)
b

[10, 20, 30]

In [123]:
arr = np.array([1, 2, 3])
arr * 10

array([10, 20, 30])

In [124]:
arr * arr

array([1, 4, 9])

In [125]:
arr - arr

array([0, 0, 0])

In [126]:
arr = np.random.randn(3,3)
arr

array([[-0.56060259,  0.45181362,  0.85494956],
       [-1.55298021, -1.28275044,  0.09774885],
       [-0.26200043,  1.46159921, -0.78007124]])

In [127]:
np.abs(arr)

array([[0.56060259, 0.45181362, 0.85494956],
       [1.55298021, 1.28275044, 0.09774885],
       [0.26200043, 1.46159921, 0.78007124]])

In [128]:
np.square(arr)

array([[0.31427526, 0.20413555, 0.73093874],
       [2.41174754, 1.64544869, 0.00955484],
       [0.06864422, 2.13627226, 0.60851114]])

In [129]:
arr1 = np.random.randint(1, 10, size=(5))
arr1

array([4, 1, 3, 7, 7])

In [130]:
arr2 = np.random.randint(1, 10, size=(5))
arr2

array([1, 6, 9, 1, 5])

In [131]:
np.add(arr1, arr2)

array([ 5,  7, 12,  8, 12])

In [132]:
np.minimum(arr1, arr2)

array([1, 1, 3, 1, 5])

In [133]:
arr = np.random.normal(2,4,size=(6,))
arr

array([-0.50969949,  6.61860107, -0.44542936,  0.98450502, 11.37290483,
        6.76379218])

In [134]:
np.modf(arr)

(array([-0.50969949,  0.61860107, -0.44542936,  0.98450502,  0.37290483,
         0.76379218]), array([-0.,  6., -0.,  0., 11.,  6.]))

In [135]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
cond = np.array([True, False, False, True])

In [136]:
result = [(x if c else y) for x, y, c in zip(arr1, arr2, cond)]
result

[1, 6, 7, 4]

In [137]:
result = np.where(cond, arr1, arr2)
result

array([1, 6, 7, 4])

In [138]:
arr = np.random.randn(4, 4)
arr

array([[ 0.71091011, -1.61141374,  0.52514722, -1.48200707],
       [ 1.65531395, -0.70807484,  0.78206514, -0.57778063],
       [-0.57520915, -0.74006714,  0.88082954,  0.11892153],
       [-2.18927778, -0.07032852,  0.4527424 ,  0.56645266]])

In [139]:
new_arr = np.where(arr > 0, 1, -1)
new_arr

array([[ 1, -1,  1, -1],
       [ 1, -1,  1, -1],
       [-1, -1,  1,  1],
       [-1, -1,  1,  1]])

In [140]:
arr = np.random.randint(1, 300, size=(3,3))
arr

array([[166,  33, 159],
       [111,  29, 195],
       [299, 299, 111]])

In [141]:
new_arr = np.where(arr > 200, 3,
                   np.where(arr > 100, 2, 1))
new_arr

array([[2, 1, 2],
       [2, 1, 2],
       [3, 3, 2]])

In [142]:
arr = np.random.randn(4, 4)
arr

array([[-0.02607772, -2.372853  ,  0.14145354,  2.15116076],
       [ 0.51029922, -0.43316864, -0.25205585,  0.90836388],
       [ 0.39917432, -0.74033444, -2.30525874,  0.3605075 ],
       [ 0.41131976,  1.19119329,  0.14672981,  0.9664657 ]])

In [143]:
arr.sum()

1.0569193804475678

In [144]:
arr.mean()

0.06605746127797299

In [145]:
arr.std()

1.1247450504274712

In [146]:
arr

array([[-0.02607772, -2.372853  ,  0.14145354,  2.15116076],
       [ 0.51029922, -0.43316864, -0.25205585,  0.90836388],
       [ 0.39917432, -0.74033444, -2.30525874,  0.3605075 ],
       [ 0.41131976,  1.19119329,  0.14672981,  0.9664657 ]])

In [147]:
arr.mean(axis=1)

array([-0.02657911,  0.18335965, -0.57147784,  0.67892714])

In [148]:
arr.sum(0)

array([ 1.29471558, -2.35516279, -2.26913124,  4.38649783])

In [149]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [150]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [151]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [152]:
arr = np.random.randn(20)
arr

array([ 0.70561778, -1.5575664 , -1.30383575,  0.16117604,  0.72044146,
        1.39715875,  0.02320483,  1.67274238, -0.23307639, -0.7110304 ,
       -1.46205799,  0.96488753,  1.03576526, -0.25936295, -0.3195715 ,
        0.56488814, -0.53047122,  1.26923247, -0.28068091,  0.84082391])

In [153]:
(arr > 0).sum()

11

In [154]:
arr = np.array([True, False, False, True])
arr

array([ True, False, False,  True])

In [155]:
arr.any()

True

In [156]:
arr.all()

False

In [157]:
arr = np.random.randn(10)
arr

array([-0.01698758, -1.05885854, -0.04676058, -0.53817172,  1.23444601,
        0.20956774, -1.37186925,  1.39811486,  1.5994996 , -0.31663337])

In [158]:
arr.sort()
arr

array([-1.37186925, -1.05885854, -0.53817172, -0.31663337, -0.04676058,
       -0.01698758,  0.20956774,  1.23444601,  1.39811486,  1.5994996 ])

In [159]:
arr = np.random.randn(5,3)
arr

array([[ 1.3268483 , -0.65161236,  0.70938893],
       [ 0.92519118,  0.4418409 , -0.08406218],
       [-1.29632815, -0.17069917, -1.17039167],
       [ 1.10217509, -0.42712203, -1.09580594],
       [ 1.05888685,  0.09851792, -1.58275576]])

In [160]:
arr.sort(1)
arr

array([[-0.65161236,  0.70938893,  1.3268483 ],
       [-0.08406218,  0.4418409 ,  0.92519118],
       [-1.29632815, -1.17039167, -0.17069917],
       [-1.09580594, -0.42712203,  1.10217509],
       [-1.58275576,  0.09851792,  1.05888685]])

In [161]:
fruits = np.array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'])
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [162]:
np.unique(fruits)

array(['apple', 'banana', 'pear'], dtype='<U6')

In [163]:
arr = np.array([2, 3, 3, 2, 8, 1])
arr

array([2, 3, 3, 2, 8, 1])

In [164]:
np.unique(arr)

array([1, 2, 3, 8])

In [165]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [167]:
np.dot(arr1,arr2)

array([[24, 30, 36],
       [51, 66, 81]])

In [168]:
from numpy.linalg import det

In [169]:
arr = np.array([[1, 2], [3, 4]])
arr

array([[1, 2],
       [3, 4]])

In [170]:
det(arr)

-2.0000000000000004

## 综合案例：图像处理

In [171]:
from PIL import Image
import numpy as np

In [173]:
im = np.array(Image.open('H:/我的视频录制/从零开始学Python数据分析/data/1.jpeg'))
print(im.shape,im.dtype)

(350, 583, 3) uint8


In [174]:
im

array([[[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [195, 195, 195]],

       ...,

       [[210, 210, 210],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [122, 122, 122],
        [124, 124, 124],
        [125, 125, 125]],

       [[211, 211, 211],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [120, 120, 120],
        [122, 122, 122],
        [124, 124, 124]],

       [[211, 211, 211],
        [211, 211, 211],
        [212, 212, 212],
        ...,
        [119, 119, 119],
        [121, 121, 121],
        [123, 123, 123]]

In [175]:
b = [255, 255, 255] - im    #数组运算
new_im = Image.fromarray(b.astype('uint8'))  
new_im.save('H:/我的视频录制/从零开始学Python数据分析/data/2.jpeg')  #保存为新图像

In [176]:
b

array([[[ 29,  29,  29],
        [ 29,  29,  29],
        [ 29,  29,  29],
        ...,
        [ 57,  57,  57],
        [ 58,  58,  58],
        [ 59,  59,  59]],

       [[ 29,  29,  29],
        [ 29,  29,  29],
        [ 29,  29,  29],
        ...,
        [ 57,  57,  57],
        [ 58,  58,  58],
        [ 59,  59,  59]],

       [[ 29,  29,  29],
        [ 29,  29,  29],
        [ 29,  29,  29],
        ...,
        [ 57,  57,  57],
        [ 58,  58,  58],
        [ 60,  60,  60]],

       ...,

       [[ 45,  45,  45],
        [ 44,  44,  44],
        [ 44,  44,  44],
        ...,
        [133, 133, 133],
        [131, 131, 131],
        [130, 130, 130]],

       [[ 44,  44,  44],
        [ 44,  44,  44],
        [ 44,  44,  44],
        ...,
        [135, 135, 135],
        [133, 133, 133],
        [131, 131, 131]],

       [[ 44,  44,  44],
        [ 44,  44,  44],
        [ 43,  43,  43],
        ...,
        [136, 136, 136],
        [134, 134, 134],
        [132, 132, 132]]